#!/usr/bin/env python3
"""Compare each student's first webpage assignment (HW2) against their final
report, and summarize the two prior-course-roster groups' average trajectories.

This closes a reproducibility gap: seismology_2026_hw2_to_final_comparison.md
was previously hand-written/generated by a script that was never committed.
Re-derives it from the already-published, already-anonymized per-record CSVs
(seismology_2026_hw2_prior_advantage_evidence.csv and
results_seismology_2026_final_primary.csv), the same inputs build_figures.py
uses for figure4/figure5, so the report and the figures always agree.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from build_figures import assignment_final_data

METRICS = [
    ("媒體豐富度(1-4)", "媒體豐富度", "分", 2),
    ("排版架構(1-4)", "排版架構", "分", 2),
    ("總字數", "可見文本字元數", "字元", 0),
    ("專有名詞密度(次/千字)", "專有名詞密度", "次/千字", 2),
    ("批判思考佔比(%)", "批判思考比例", "個百分點", 2),
]
DELTA_COLS = ["媒體_變化", "排版_變化", "字數_變化", "術語密度_變化", "批判思考_變化"]
PRIOR_GROUP = "上學期作品名單內"
NEW_GROUP = "未見於上學期作品名單"


def direction_counts(series: pd.Series) -> tuple[int, int, int]:
    return int((series > 0).sum()), int((series == 0).sum()), int((series < 0).sum())


def fmt(value: float, digits: int = 2) -> str:
    sign = "+" if value > 0 else ""
    return f"{sign}{value:.{digits}f}"


def make_report(common: pd.DataFrame) -> str:
    prior = common[common["組別"].eq(PRIOR_GROUP)]
    new = common[common["組別"].eq(NEW_GROUP)]

    lines = [
        "# 下學期第一個網頁作業與期末報告之變化",
        "",
        "## 分析對象",
        "",
        f"- 同時具有第一個網頁作業與期末報告：{len(common)} 人",
        f"- 上學期作品名單內（先備組）：{len(prior)} 人",
        f"- 未見於上學期作品名單（新加入組）：{len(new)} 人",
        "- 全部資料均以一次性匿名代碼呈現",
        "",
        "兩次任務並非相同前後測：",
        "",
        "- 第一個網頁作業要求完整介紹地震學課本第一章。",
        "- 期末報告要求整合整學期成果、實作與反思。",
        "",
        "因此，以下結果描述作品型態如何改變，不直接代表能力增減。",
        "",
        "## 全體學生的變化",
        "",
        "| 指標 | 平均變化（期末－第一個作業） | 增加 | 持平 | 減少 |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for metric, label, unit, digits in METRICS:
        delta_col = {
            "媒體豐富度(1-4)": "媒體_變化",
            "排版架構(1-4)": "排版_變化",
            "總字數": "字數_變化",
            "專有名詞密度(次/千字)": "術語密度_變化",
            "批判思考佔比(%)": "批判思考_變化",
        }[metric]
        up, same, down = direction_counts(common[delta_col])
        lines.append(
            f"| {label} | {fmt(common[delta_col].mean(), digits)} {unit} | {up} | {same} | {down} |"
        )

    media_up, media_same, _ = direction_counts(common["媒體_變化"])
    layout_same = direction_counts(common["排版_變化"])[1]
    text_down = direction_counts(common["字數_變化"])[2]
    term_up, _, term_down = direction_counts(common["術語密度_變化"])
    reflect_up = direction_counts(common["批判思考_變化"])[0]

    lines += [
        "",
        "### 1. 媒體豐富度",
        "",
        f"媒體分數平均{fmt(common['媒體_變化'].mean(),2)} 分，{len(common)} 人中有 {media_up} 人增加、"
        f"{media_same} 人持平。修正裝飾性 SVG 圖示誤判後，媒體分數的成長幅度較保守，"
        "仍以持續增加互動、視覺或多媒體元素為主要方向，但不是全面且一致的躍升。",
        "",
        "### 2. 排版架構",
        "",
        f"{layout_same} 人維持原分數，整體平均沒有變化。第一個作業多數作品已具備導覽與分區，"
        "期末因而呈現明顯的尺規天花板。",
        "",
        "### 3. 可見文本字元數",
        "",
        f"{text_down} 人的期末作品字元數較少，全體平均減少 {abs(common['字數_變化'].mean()):.0f} 字元。"
        "這不宜解讀為內容退步：",
        "",
        "- 第一個作業需要系統介紹完整章節，天然偏長。",
        "- 期末作品可能採時間軸、卡片、連結入口、影片或互動展示，靜態文字不一定較多。",
        "- 新加入組有一份極長期末作品，使平均值受到離群值影響。",
        "",
        "### 4. 專有名詞密度",
        "",
        f"{term_up} 人增加、{term_down} 人減少；中位數變化與平均值方向可能不同，"
        "顯示少數大幅下降作品拉低平均，因此較適合解讀為「高度分化」，而非整體下降。",
        "",
        "### 5. 批判思考比例",
        "",
        f"{reflect_up} 人增加，平均增加 {common['批判思考_變化'].mean():.2f} 個百分點。"
        "期末任務包含學期回顧、實作心得與工具反思，比第一個課本介紹作業更容易出現比較、限制、改進及個人洞見。",
        "",
        "本比例仍是關鍵詞啟發式估計，不能取代人工內容分析。",
        "",
        "## 兩組平均軌跡",
        "",
        "| 指標 | 先備組：作業→期末 | 新加入組：作業→期末 |",
        "| --- | ---: | ---: |",
    ]
    for metric, label, unit, digits in METRICS:
        col_a, col_f = f"{metric}_作業", f"{metric}_期末"
        p_a, p_f = prior[col_a].mean(), prior[col_f].mean()
        n_a, n_f = new[col_a].mean(), new[col_f].mean()
        if metric == "總字數":
            lines.append(f"| {label} | {p_a:,.0f} → {p_f:,.0f} | {n_a:,.0f} → {n_f:,.0f} |")
        elif metric == "批判思考佔比(%)":
            lines.append(f"| {label} | {p_a:.2f}% → {p_f:.2f}% | {n_a:.2f}% → {n_f:.2f}% |")
        else:
            lines.append(f"| {label} | {p_a:.2f} → {p_f:.2f} | {n_a:.2f} → {n_f:.2f} |")

    media_gain_prior = prior["媒體_變化"].mean()
    media_gain_new = new["媒體_變化"].mean()
    reflect_gain_prior = prior["批判思考_變化"].mean()
    reflect_gain_new = new["批判思考_變化"].mean()
    media_lead = "先備組" if media_gain_prior > media_gain_new else "新加入組"

    lines += [
        "",
        "### 組間變化的主要特徵",
        "",
        f"1. **{media_lead}的媒體增幅較大**：先備組 {fmt(media_gain_prior,2)} 分，"
        f"新加入組 {fmt(media_gain_new,2)} 分。",
        "2. **排版兩組皆穩定**：顯示第一個作業階段已建立基本網站架構。",
        f"3. **先備組第一個作業篇幅較大**，到期末平均{'下降' if prior['字數_變化'].mean()<0 else '上升'}；"
        f"新加入組平均{'上升' if new['字數_變化'].mean()>0 else '下降'}，但受到極長作品影響。",
        "4. **兩組術語密度平均皆下降**；但個別學生結果呈現分化。",
        f"5. **反思訊號增幅**：先備組 {fmt(reflect_gain_prior,2)} 個百分點，"
        f"新加入組 {fmt(reflect_gain_new,2)} 個百分點。",
        "",
        "## 結論",
        "",
        "第一個網頁作業至期末期間，最一致的正向變化是反思訊號增加；排版大致穩定，"
        "媒體豐富度的成長集中在先備組。篇幅與術語密度受到作業目的及呈現方式影響，不能當作單向進步量尺。",
        "",
        f"{media_lead}在媒體豐富度上的增幅較大，"
        + (
            "與「先備經驗的早期差距在課程中逐步縮小」的描述不一致——修正裝飾性 SVG 圖示誤判為進階媒體整合的計分錯誤後，"
            "先備組到期末的媒體優勢反而擴大，而非新加入組追平。"
            if media_lead == "先備組"
            else "與「先備經驗的早期差距在課程中逐步縮小」的描述一致。"
        ),
        "但兩次任務不同、樣本小且非隨機分組，不能據此推論因果。",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="比較第一個網頁作業與期末報告的個別及組別變化")
    parser.add_argument("--assignment", default="seismology_2026_hw2_prior_advantage_evidence.csv")
    parser.add_argument("--final", default="results_seismology_2026_final_primary.csv")
    parser.add_argument("--report", default="seismology_2026_hw2_to_final_comparison.md")
    args = parser.parse_args()

    assignment = pd.read_csv(args.assignment, dtype={"匿名代碼": str})
    final = pd.read_csv(args.final, dtype={"匿名代碼": str})
    common = assignment_final_data(assignment, final)

    Path(args.report).write_text(make_report(common), encoding="utf-8")
    print(f"[saved] {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
